// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trmhqulnmjgztddqfwwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRybWhxdWxubWpnenRkZHFmd3d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTM1MzcsImV4cCI6MjA3MzUyOTUzN30.KXKQKF9HMbAsiVEKitNoIIw9j56FRoFYyLJqgPccS18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});